import "../src/app/styles/globals.css";
import Header from "./Header";
// import Link from "next/link";
// import Head from "next/head";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Maddie's Website</title>
      </head>
      {/* <header>
        <nav>
          <Link href="/">
            <a>Home</a>
          </Link>
          <link href="/about">
            <a>About</a>
          </link>{" "}
        </nav>
      </header> */}
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
